### ISSUE TITLE
Unable to save translation if the page does not already exist in translated language

### ISSUE THREAD

**Issue by angusmcb** [ricardo118/grav-plugin-translator#2]
I am getting errors making the plugin unusable. I can log in and select a page to translate, but am unable to save or submit the page.

I am using the latest version of Grav and PHP 7.4.1.

The error message is below:

Fatal error: Uncaught Error: Undefined class constant 'Monolog\Utils::DEFAULT_JSON_FLAGS' in C:\Users\amcbride\Web\grav-translator-test\vendor\monolog\monolog\src\Monolog\Handler\AbstractHandler.php:194 Stack trace: #0 C:\Users\amcbride\Web\grav-translator-test\vendor\monolog\monolog\src\Monolog\Handler\AbstractHandler.php(113): Monolog\Handler\AbstractHandler->getDefaultFormatter() #1 C:\Users\amcbride\Web\grav-translator-test\vendor\monolog\monolog\src\Monolog\Handler\AbstractProcessingHandler.php(37): Monolog\Handler\AbstractHandler->getFormatter() #2 C:\Users\amcbride\Web\grav-translator-test\vendor\monolog\monolog\src\Monolog\Logger.php(344): Monolog\Handler\AbstractProcessingHandler->handle(Array) #3 C:\Users\amcbride\Web\grav-translator-test\vendor\monolog\monolog\src\Monolog\Logger.php(470): Monolog\Logger->addRecord(500, 'Process could n...', Array) #4 C:\Users\amcbride\Web\grav-translator-test\system\src\Grav\Common\Errors\Errors.php(73): Monolog\Logger->addCritical('Process could n...') #5 C:\Users\amcbride\Web in C:\Users\amcbride\Web\grav-translator-test\vendor\monolog\monolog\src\Monolog\Handler\AbstractHandler.php on line 194

**Comment by angusmcb** [comment]
I realised that the above error is coming from the logging of another error. After turning off logging, I found this error when I try to save a translation:

{"error":{"type":"Whoops\\Exception\\ErrorException","message":"array_replace_recursive(): Expected parameter 2 to be an array, null given","code":2,"file":"C:\\Users\\amcbride\\Web\\grav-translator-test\\user\\plugins\\translator\\classes\\Controller.php","line":153}}

**Comment by angusmcb** [comment]
Maybe I'm getting closer to the problem - the error only seems to occur if the page that is being translated does not already exist in the translated language.

**Comment by Netmees** [comment]
> I realised that the above error is coming from the logging of another error. After turning off logging, I found this error when I try to save a translation:
> 
> {"error":{"type":"Whoops\Exception\ErrorException","message":"array_replace_recursive(): Expected parameter 2 to be an array, null given","code":2,"file":"C:\Users\amcbride\Web\grav-translator-test\user\plugins\translator\classes\Controller.php","line":153}}

have the same error code... and it happens even if the translated page its created, 

i also get the error of 404 on task:translator.keep.alive url

its could be related to php Version

¿ whats the optimal php version for working properly ?
 Whats the maximun GRAV version can work properly ?
Whats the modules that gets into trouble when are active ?
simple search.... etc
